###
### Restaurants
###

###
GET http://localhost:5000/api/v1/restaurants

###
GET http://localhost:5000/api/v1/restaurants/1

###
POST http://localhost:5000/api/v1/restaurants
Authorization:
Content-Type: application/json

{
    "name": "Satan's Grill",
    "description": "Your go-to place for all spicy! Newer iterations of spicy dishes feature not just heat, but pickled, savory, sour, smoky and sweet elements as well. In other words, complex flavors are what’s hot right now—both literally and figuratively.",
    "location": "Main Street",
    "website": "https://google.com"
}

###
PATCH http://localhost:5000/api/v1/restaurants/1
Authorization:
Content-Type: application/json

{
    "name": "Satan's Updated Grill"
}

###
DELETE http://localhost:5000/api/v1/restaurants/1
Authorization:

###
### Reviews
###

###
GET http://localhost:5000/api/v1/reviews

###
GET http://localhost:5000/api/v1/reviews/restaurant/1

###
GET http://localhost:5000/api/v1/reviews/1

###
POST http://localhost:5000/api/v1/reviews
Authorization:
Content-Type: application/json

{
    "restaurant_id": 1,
    "rating": "5",
    "review": "Very spicy indeed.. As I had found out later at home.."
}

###
PATCH http://localhost:5000/api/v1/reviews/1
Authorization:
Content-Type: application/json

{
    "name": "John Doe"
}

###
DELETE http://localhost:5000/api/v1/reviews/1
Authorization:

###
### Auth
###

###
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "username": "Michal",
    "email": "email@example.com",
    "password": "password",
    "confirmPassword": "password"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "email@example.com",
    "password": "password"
}